import {
  Activity,
  Award,
  BarChart3,
  Briefcase,
  Building2,
  Cloud,
  Code2,
  Globe,
  Heart,
  Landmark,
  Layers,
  Lightbulb,
  Mail,
  Megaphone,
  MessageCircle,
  MonitorSmartphone,
  MousePointerClick,
  Palette,
  PoundSterling,
  Rocket,
  Search,
  Server,
  Share2,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Users,
  Video,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Names must match ICON_NAMES in src/lib/services/sections/defs.ts. */
export const ICONS: Record<string, LucideIcon> = {
  Activity,
  Award,
  BarChart3,
  Briefcase,
  Building2,
  Cloud,
  Code2,
  Globe,
  Heart,
  Landmark,
  Layers,
  Lightbulb,
  Mail,
  Megaphone,
  MessageCircle,
  MonitorSmartphone,
  MousePointerClick,
  Palette,
  PoundSterling,
  Rocket,
  Search,
  Server,
  Share2,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Users,
  Video,
  Wrench,
  Zap,
};

export function getIcon(name: string | undefined, fallback: LucideIcon = Sparkles): LucideIcon {
  return (name && ICONS[name]) || fallback;
}
